### PR TITLE
recompile element inside apply

### PR DESCRIPTION
**Pull request by cjroth**
I had an issue where the element was not being updated with the disabled attribute or class because `elementToDisable` was not referencing the current element in the scope `$apply`. This fixed it.

This was occurring with Angular 1.3.8.

Not sure, but it also sounds like it could be related to #10 since `ng-if` creates its own child scope.

### CODE REVIEW

**Comment by kirstein** [comment]
Hey! Could you please add a test case for the issue at hand?

**Comment by 23tux** [comment]
+1
In my case, this also solves the `ng-if` problem, when a button is wrapped inside an element that has an `ng-if` attribute.

**Comment by mburgosh** [comment]
The tests I added fails to expose this issue. I have to admit that I'm not completely familiar with the cause (some doc would be useful).

If you can inspire from the tests, please modify them. If not revert them.

**Comment by kirstein** [comment]
Those tests seem perfectly ok. Please include them in this PR and I will merge it.

**Comment by mburgosh** [comment]
I checked out the PR master and ran the tests, and they fail.

**Pull request closed without merging**
