### PR TITLE
Pass the event along instead of the event name

### PR DESCRIPTION
**Pull request by stnor**
Hi!
Here's a pull request for #17, which properly passes on the event instead of the event name

Thanks,
Stefan

### CODE REVIEW

**Comment by mburgosh** [comment]
Great thanks for this fix!
Will build and bump the version when I get home.

**Comment by stnor** [comment]
Great! Thanks!

**Comment by stnor** [comment]
Any chance getting a version bump so I can use bower update again? :)

**Comment by mburgosh** [comment]
sorry for the delay

**Pull request merged**
